[2024-07-25T02:18:35.376+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T02:18:35.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Pipeline.first_task scheduled__2024-07-25T02:17:00+00:00 [queued]>
[2024-07-25T02:18:35.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Pipeline.first_task scheduled__2024-07-25T02:17:00+00:00 [queued]>
[2024-07-25T02:18:35.545+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-25T02:18:35.565+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): first_task> on 2024-07-25 02:17:00+00:00
[2024-07-25T02:18:35.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-25T02:18:35.577+0000] {standard_task_runner.py:64} INFO - Started process 257 to run task
[2024-07-25T02:18:35.576+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Pipeline', 'first_task', 'scheduled__2024-07-25T02:17:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpzqfnxmy6']
[2024-07-25T02:18:35.579+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask first_task
[2024-07-25T02:18:35.630+0000] {task_command.py:426} INFO - Running <TaskInstance: Pipeline.first_task scheduled__2024-07-25T02:17:00+00:00 [running]> on host f7d3c5e5ad21
[2024-07-25T02:18:35.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Pipeline' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T02:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T02:17:00+00:00'
[2024-07-25T02:18:35.739+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T02:18:36.381+0000] {logging_mixin.py:188} INFO - Obtained data
[2024-07-25T02:18:36.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T02:18:36.388+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 37, in get_data
    print('\n', data.head(1))
                ^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'head'
[2024-07-25T02:18:36.445+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Pipeline, task_id=first_task, run_id=scheduled__2024-07-25T02:17:00+00:00, execution_date=20240725T021700, start_date=20240725T021835, end_date=20240725T021836
[2024-07-25T02:18:36.478+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task first_task ('bytes' object has no attribute 'head'; 257)
[2024-07-25T02:18:36.518+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-25T02:18:36.559+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T02:18:36.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
